M48
; DRILL file {KiCad 9.0.3} date 2025-08-20T13:57:26+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-20T13:57:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X61.19Y-50.234
X61.19Y-52.266
X68.81Y-51.25
T2
X93.8Y-74.4
X117.8Y-49.0
M30
